version: "3.5"

services:
  dev-container:
    container_name: dev-container
    build: ./
    volumes:
      - ../:/project
    ports:
      - "8000:8000"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
